### ISSUE TITLE
Error in `enhanced-resolve` when using vega 3.0.9+ in a webpack-bundled app

### ISSUE THREAD

**Issue by pelotom** [vega/vega#1118]
Since upgrading Vega from v3.0.8, I'm now getting this error when I try to bundle my app with Webpack:

```
node_modules/enhanced-resolve/lib/Resolver.js:181
	var idxQuery = identifier.indexOf("?");
	                          ^

TypeError: Cannot read property 'indexOf' of null
    at Resolver.parse (node_modules/enhanced-resolve/lib/Resolver.js:181:28)
    at Resolver.<anonymous> (node_modules/enhanced-resolve/lib/ParsePlugin.js:14:25)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (node_modules/tapable/lib/Tapable.js:256:13)
    at runNormal (node_modules/enhanced-resolve/lib/Resolver.js:130:20)
    at Resolver.doResolve (node_modules/enhanced-resolve/lib/Resolver.js:116:3)
    at Resolver.<anonymous> (node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:12)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (node_modules/tapable/lib/Tapable.js:256:13)
    at runNormal (node_modules/enhanced-resolve/lib/Resolver.js:130:20)
    at Resolver.doResolve (node_modules/enhanced-resolve/lib/Resolver.js:116:3)
    at Resolver.<anonymous> (node_modules/enhanced-resolve/lib/AliasFieldPlugin.js:44:12)
    at next (node_modules/tapable/lib/Tapable.js:254:14)
    at Resolver.<anonymous> (node_modules/enhanced-resolve/lib/ConcordModulesPlugin.js:23:28)
    at next (node_modules/tapable/lib/Tapable.js:254:14)
    at Resolver.<anonymous> (node_modules/enhanced-resolve/lib/AliasPlugin.js:55:10)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (node_modules/tapable/lib/Tapable.js:256:13)
    at runNormal (node_modules/enhanced-resolve/lib/Resolver.js:130:20)
```

**Comment by pelotom** [comment]
Looks like this is a duplicate of https://github.com/vega/vega-canvas/issues/1.
