### ISSUE TITLE
Canvas-prebuilt dependency install error

### ISSUE THREAD

**Issue by harry75369** [vega/vega#1291]
When installing vega dependencies using yarn, an optional dependency `canvas-prebuilt` will throw errors as follows
```
yarn install v1.6.0
(node:97447) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/2] ⠂ canvas: CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
[2/2] ⠂ canvas-prebuilt: node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-node-v64-darwin-x64.tar.gz
[-/2] ⠂ waiting...
[-/2] ⠂ waiting...
warning Error running install script for optional dependency: "/Users/harry/vega/node_modules/canvas-prebuilt: Command failed.
Exit code: 1
Command: node_modules/.bin/node-pre-gyp install
Arguments:
Directory: /Users/harry/vega/node_modules/canvas-prebuilt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.1.0 | darwin | x64
node-pre-gyp info check checked for \"/Users/harry/vega/node_modules/canvas-prebuilt/canvas/build/Release/canvas-prebuilt.node\" (not found)
node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/harry/vega/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:187:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/harry/vega/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:538:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:425:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:277:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:262:11)
node-pre-gyp ERR! System Darwin 15.6.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/10.1.0/bin/node\" \"/Users/harry/vega/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp\" \"install\"
node-pre-gyp ERR! cwd /Users/harry/vega/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v10.1.0
```
It is supposed to be the same error for npm install.

The error is because canvas-prebuilt file is no longer available (404 Error). And this optional dependency should be upgraded or deleted.

**Comment by jheer** [comment]
Thanks! Vega v4.0.0-rc.2 has been released, which includes an update to the latest canvas-prebuilt version. With this update, I'm not seeing any installation hiccups on my end.
