### ISSUE TITLE
vg2png doesn't work on node

### ISSUE THREAD

**Issue by domoritz** [vega/vega#1294]
node doesn't support the new import syntax yet

```
../node_modules/.bin/vl2png spec/vega-lite/area_vertical.vl.json images/examples/vl/area_vertical.vl.png
parallel: Starting no more jobs. Waiting for 1 jobs to finish.
ETA: 0s Left: 297 AVG: 0.00s  local:1/3/100%/0.7s /Users/domoritz/Developer/UW/editor/node_modules/vega/index.js:3
import {extend} from 'vega-util';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/domoritz/Developer/UW/editor/node_modules/vega/bin/vg2png:17:12)
WARN A time scale is used with area mark. This can be misleading as the width of the area can be arbitrary based on the scale domain. You may want to use point mark instead.
events.js:183
      throw er; // Unhandled 'error' event
      ^

```

**Comment by domoritz** [comment]
It should work when I run `yarn build`, though.

**Comment by jheer** [comment]
It is working fine for me. The package.json file points to `"main": "build/vega.js"`, which contains the output of rollup (no `import` statements). Are you missing the build files (these are included in the npm release)??

**Comment by domoritz** [comment]
I'm working on the Vega-Editor and we use the github releases because we need the examples. Running `yarn` used to build vega bur doesn't anymore so my builds failed. Sorry for the noise.
