### ISSUE TITLE
Syntax errors when using YUICompressor

### ISSUE THREAD

**Issue by jeromer** [vega/vega#132]
Vega version : 1.3.2
YUICompressor version: 2.4 (I also tested with the latest 2.4.8. Same issue)

    java -jar ./bin/yuicompressor-2.4.jar --charset=utf-8 --verbose ./static/js/vega.js

    [ERROR] 40:11:missing name after . operator

    [ERROR] 40:41:missing ) in parenthetical

    [ERROR] 2747:30:missing name after . operator

    [ERROR] 2748:16:syntax error

    [ERROR] 6967:11:invalid return

    [ERROR] 6968:1:syntax error

    [ERROR] 1:0:Compilation produced 6 syntax errors.
    org.mozilla.javascript.EvaluatorException: Compilation produced 6 syntax errors.
        at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:135)
        at org.mozilla.javascript.Parser.parse(Parser.java:402)
        at org.mozilla.javascript.Parser.parse(Parser.java:347)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:532)
        at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:20)
    zsh: exit 2     java -jar ./bin/yuicompressor-2.4.jar --charset=utf-8 --verbose

**Comment by arvind** [comment]
Please re-open this issue if you're still experiencing these issues with Vega 2.0. We've run jshint against the source code, so we should hopefully be in better shape than we were.
