### ISSUE TITLE
canvas-prebuilt not available for Node 11

### ISSUE THREAD

**Issue by FezVrasta** [vega/vega#1482]
Whenever I try to install vega on Node 11 I get an warning about canvas-prebuilt not supporting Node 11.

```
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@11.1.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for \"/node_modules/canvas-prebuilt/canvas/build/Release/canvas-prebuilt.node\" (not found)
node-pre-gyp http GET https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-darwin-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:187:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:449:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:283:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:264:11)
node-pre-gyp ERR! System Darwin 18.0.0
node-pre-gyp ERR! command \"/usr/local/bin/node\" \"/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp\" \"install\"
node-pre-gyp ERR! cwd /node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v11.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-darwin-x64.tar.gz"
info This module is OPTIONAL, you can safely ignore this error
```

**Comment by FezVrasta** [comment]
Reading on the `canvas-prebuilt` repository it seems to be deprecated, they recommend to use `canvas`.

**Comment by jheer** [comment]
Thanks! In our development branch we've already removed canvas-prebuilt and upgraded to canvas 2.2. These will be included in the next release.
