### ISSUE TITLE
vg2pdf error

### ISSUE THREAD

**Issue by eitanlees** [vega/vega#2282]
## Context
I was trying to use the new [altair_saver](https://github.com/altair-viz/altair_saver) package and was running into some trouble. A detailed account of my issues can be found at https://github.com/altair-viz/altair_saver/issues/13 . Please bare with me as I am a little out of my element. 

## Installation
I used `conda` to install Node.js with no problem 

```bash
conda install -c conda-forge nodejs
```

Then I used npm to install a few packages. 

```bash
$ npm install -g vega vega-lite vega-cli canvas
npm WARN npm npm does not support Node.js v13.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
/Users/eitanlees/miniconda3/bin/vg2pdf -> /Users/eitanlees/miniconda3/lib/node_modules/vega-cli/bin/vg2pdf
/Users/eitanlees/miniconda3/bin/vg2png -> /Users/eitanlees/miniconda3/lib/node_modules/vega-cli/bin/vg2png
/Users/eitanlees/miniconda3/bin/vg2svg -> /Users/eitanlees/miniconda3/lib/node_modules/vega-cli/bin/vg2svg
/Users/eitanlees/miniconda3/bin/vl2png -> /Users/eitanlees/miniconda3/lib/node_modules/vega-lite/bin/vl2png
/Users/eitanlees/miniconda3/bin/vl2svg -> /Users/eitanlees/miniconda3/lib/node_modules/vega-lite/bin/vl2svg
/Users/eitanlees/miniconda3/bin/vl2vg -> /Users/eitanlees/miniconda3/lib/node_modules/vega-lite/bin/vl2vg
+ canvas@2.6.1
+ vega-lite@4.0.2
+ vega@5.9.0
+ vega-cli@5.9.0
updated 4 packages in 5.383s
```

Not sure if that is how things should look but I think it worked. 

## Problem

I wanted to test if I could convert a Vega-Lite spec to PDF but ran into issues. I expected the command below to result in the following output. 
![visualization (43)](https://user-images.githubusercontent.com/2041969/71837355-3c144880-3084-11ea-8bfb-424b5a3124ef.png)

But instead I get this error. 

```bash
$ echo '{"data": {"url": "https://vega.github.io/vega-datasets/data/cars.json"}, "mark": "point"}' | vl2vg | vg2pdf > out.pdf

TypeError: Cannot read property 'getContext' of null
    at resize (/Users/eitanlees/miniconda3/lib/node_modules/vega/node_modules/vega-scenegraph/build/vega-scenegraph.js:3607:26)
    at CanvasRenderer.prototype$6.resize (/Users/eitanlees/miniconda3/lib/node_modules/vega/node_modules/vega-scenegraph/build/vega-scenegraph.js:3657:5)
    at CanvasRenderer.prototype$4.initialize (/Users/eitanlees/miniconda3/lib/node_modules/vega/node_modules/vega-scenegraph/build/vega-scenegraph.js:3235:17)
    at CanvasRenderer.prototype$6.initialize (/Users/eitanlees/miniconda3/lib/node_modules/vega/node_modules/vega-scenegraph/build/vega-scenegraph.js:3652:28)
    at initializeRenderer (/Users/eitanlees/miniconda3/lib/node_modules/vega/node_modules/vega-view/build/vega-view.js:632:8)
    at renderHeadless (/Users/eitanlees/miniconda3/lib/node_modules/vega/node_modules/vega-view/build/vega-view.js:738:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async View.renderToCanvas [as toCanvas] (/Users/eitanlees/miniconda3/lib/node_modules/vega/node_modules/vega-view/build/vega-view.js:773:15)
```

I am not sure why this is happening. Any advice?

## Versions
```bash
$ vl2vg --version
4.0.2
$ vg2pdf --version
5.9.0
```

**Comment by eitanlees** [comment]
I figured out what was wrong and it has nothing to do with this project. I had something in my `.npmrc` file that prevented the packages from installing correctly. There is no issue here!
