### ISSUE TITLE
Canvas error when using toCanvas()

### ISSUE THREAD

**Issue by AnonNewGuy** [vega/vega#2781]
# Shortened code snippet:
```js
const view = new vega
    .View(vega.parse(chartData))
    .renderer('none')
    .initialize()
view
    .toCanvas()
    .then(canvas => {
        consle.log('Generating image...!')
        fs.writeFile('./growth.png', canvas.toBuffer(), () => {
         // Handling
        })
    })
```

# Full error log: 
```
Error: CanvasRenderer is missing a valid canvas or context
	at Object.error (/home/social/IRFGrowth/node_modules/vega-util/build/vega-util.js:40:11)
	at CanvasRenderer.prototype$6.resize (/home/social/IRFGrowth/node_modules/vega-scenegraph/build/vega-scenegraph.js:3763:26)
	at CanvasRenderer.prototype$4.initialize (/home/social/IRFGrowth/node_modules/vega-scenegraph/build/vega-scenegraph.js:3294:17)
	at CanvasRenderer.prototype$6.initialize (/home/social/IRFGrowth/node_modules/vega-scenegraph/build/vega-scenegraph.js:3750:28)
	at initializeRenderer (/home/social/IRFGrowth/node_modules/vega-view/build/vega-view.js:653:8)
	at renderHeadless (/home/social/IRFGrowth/node_modules/vega-view/build/vega-view.js:776:12)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async View.renderToCanvas [as toCanvas] (/home/social/IRFGrowth/node_modules/vega-view/build/vega-view.js:811:15)
```

To fix this, I've tried:
- Reinstalling all dependencies in my project (including canvas, vega, fs, node-pre-gyp)
- Using various node versions
- Using various canvas versions

This identical error persists no matter the case, seeking some help.

Node version: 12.18.3
NPM version: 6.14.7
Vega version: 5.13.0
Canvas version: 2.6.1

**Comment by domoritz** [comment]
Which is are you on?

**Comment by niraj-gawande** [comment]
Facing same issue on windows 10.

**Comment by AnonNewGuy** [comment]
> Which OS are you on?

Ubuntu Desktop 20.04, running from SSH

**Comment by domoritz** [comment]
Hmm, I don't know about windows but our tests are running on ubuntu. Could you take a look at https://github.com/vega/vega/blob/master/.github/workflows/test.yml and see whether the build steps help you?

**Comment by AnonNewGuy** [comment]
Appears to have worked! Specifically, restarting the process after running `yarn --frozen-lockfile` got rid of the issue. Perhaps it was a faulty installation of canvas (I did have node-pre-gyp difficulties beforehand). (I'd still love to hear if @niraj-gawande was able to fix it using the same method)

**Comment by Maxim-Mazurok** [comment]
Same error on Win 10, `npm ci` resolved the issue
