### ISSUE TITLE
Wordcloud not working in node / vg2png

### ISSUE THREAD

**Issue by nyurik** [vega/vega#279]
Trying to render [wordcloud example] (http://trifacta.github.io/vega/editor/?spec=wordcloud) in nodejs fails:
/home/yurik/wmf/vega/vega.js:4444
  var layout = d3.layout.cloud().size([900, 500]),
                         ^
TypeError: Object #<Object> has no method 'cloud'
    at Object.vg.data.wordcloud (/home/yurik/wmf/vega/vega.js:4444:26)
    at vg.parse.transform (/home/yurik/wmf/vega/vega.js:8076:29)
    at Array.map (native)
    at Object.vg.parse.dataflow (/home/yurik/wmf/vega/vega.js:7381:34)
    at /home/yurik/wmf/vega/vega.js:7354:27
    at Array.forEach (native)
    at Object.vg.parse.data (/home/yurik/wmf/vega/vega.js:7343:16)
    at parse (/home/yurik/wmf/vega/vega.js:7898:22)
    at Object.vg.parse.spec (/home/yurik/wmf/vega/vega.js:7904:23)
    at Object.vg.headless.render (/home/yurik/wmf/vega/vega.js:10996:12)

**Comment by arvind** [comment]
Have you installed [`d3.layout.cloud`](https://www.npmjs.com/package/d3.layout.cloud)? It looks like that's missing from `package.json`.

**Comment by nyurik** [comment]
I have installed it locally, but from I could see, the code never uses
require() on it, just assumes it has already been loaded.

**Comment by arvind** [comment]
We've removed support for `wordcloud` in Vega 2.0 as the `d3.layout.cloud` plugin ran asychronously, which is currently incompatible with our new dataflow infrastructure. We may consider reintroducing it in a future release.

**Comment by saper** [comment]
I believe this has been resolved with https://github.com/vega/vega/pull/317 

I was able to generate the wordcloud with b1a6a7c51543bd5141fe7cc33d358ab66d60e1d
