### ISSUE TITLE
SyntaxError: Unexpected token '?' with command vg2svg

### ISSUE THREAD

**Issue by dxlong2000** [vega/vega#3582]
Dear authors,

Thank you for your great work! I have installed ```vega-cli``` by ```yarn global add vega-cli```. When I run the command ```vg2svg``` to generate the SVG file, I got this error:
```MacBook-Pro-cua-Do:FYP doxuanlong$   vg2svg -b /Users/doxuanlong/Desktop/NTU/FYP/processed_data_BAR/ArgentinaFoodStimulantsResidualsThousandMetricTons2014to2018_bar__bar_.json -s /Users/doxuanlong/Desktop/NTU/FYP/Agumentation/results/test.json 
/usr/local/lib/node_modules/vega-cli/node_modules/vega-label/build/vega-label.js:593
      let textWidth = d.textWidth ?? 0,
                                   ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vega-cli/node_modules/vega/build/vega-node.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
```

Do you have any idea about it?

Thanks a lot!

**Comment by domoritz** [comment]
You may need to update your node version to support this new syntax feature.

**Comment by dxlong2000** [comment]
Hi @domoritz ,

After updating it and run, I got this error:

```
Error: Duplicate data set name: undefined
    at Object.error (/usr/local/lib/node_modules/vega-cli/node_modules/vega-util/build/vega-util.js:39:11)
    at Scope.addDataPipeline (/usr/local/lib/node_modules/vega-cli/node_modules/vega-parser/build/vega-parser.js:3758:18)
    at parseData (/usr/local/lib/node_modules/vega-cli/node_modules/vega-parser/build/vega-parser.js:2489:11)
    at /usr/local/lib/node_modules/vega-cli/node_modules/vega-parser/build/vega-parser.js:3227:44
    at Array.forEach (<anonymous>)
    at parseScope (/usr/local/lib/node_modules/vega-cli/node_modules/vega-parser/build/vega-parser.js:3227:31)
    at parseView (/usr/local/lib/node_modules/vega-cli/node_modules/vega-parser/build/vega-parser.js:3293:5)
    at Object.parse (/usr/local/lib/node_modules/vega-cli/node_modules/vega-parser/build/vega-parser.js:4027:12)
    at render (/usr/local/lib/node_modules/vega-cli/src/render.js:47:37)
    at /usr/local/lib/node_modules/vega-cli/src/render.js:62:19
```

Do you have any idea?

Thanks!

**Comment by dxlong2000** [comment]
My data looks like this:

```
{"title": "Austria - Agriculture, Forestry and Fishing FDI Income Payments", "data": [{"Austria - Agriculture, Forestry and Fishing FDI Income Payments": "2012", "Million US Dollars": 0.0}, {"Austria - Agriculture, Forestry and Fishing FDI Income Payments": "2013", "Million US Dollars": 0.0}, {"Austria - Agriculture, Forestry and Fishing FDI Income Payments": "2014", "Million US Dollars": 0.0}, {"Austria - Agriculture, Forestry and Fishing FDI Income Payments": "2015", "Million US Dollars": 0.0}, {"Austria - Agriculture, Forestry and Fishing FDI Income Payments": "2016", "Million US Dollars": 0.0}, {"Austria - Agriculture, Forestry and Fishing FDI Income Payments": "2017", "Million US Dollars": 0.0}, {"Austria - Agriculture, Forestry and Fishing FDI Income Payments": "2018", "Million US Dollars": 0.0}]}
```

**Comment by domoritz** [comment]
Please try one of the example specs and validate your spec against the Vega json schema.

**Comment by dxlong2000** [comment]
Hi @domoritz ,

Although I can render by the online editor this JSON data, the command ```vg2svg``` gave me the attached SVG file. Do you have any suggestions?

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" class="marks" width="850" height="17" viewBox="0 0 850 17"><g fill="none" stroke-miterlimit="10" transform="translate(0,17)"><g class="mark-group role-frame root" role="graphics-object" aria-roledescription="group mark container"><g transform="translate(0,0)"><path class="background" aria-hidden="true" d="M0,0h850v0h-850Z"/><g><g class="mark-group role-title"><g transform="translate(425,-17)"><path class="background" aria-hidden="true" d="M0,0h0v0h0Z" pointer-events="none"/><g><g class="mark-text role-title-text" role="graphics-symbol" aria-roledescription="title" aria-label="Title text 'Argentina - Fermented Beverages Residuals'" pointer-events="none"><text text-anchor="middle" transform="translate(0,10)" font-family="Luminari" font-size="13px" font-weight="bold" fill="#000" opacity="1">Argentina - Fermented Beverages Residuals</text></g></g><path class="foreground" aria-hidden="true" d="" pointer-events="none" display="none"/></g></g></g><path class="foreground" aria-hidden="true" d="" display="none"/></g></g></g></svg>
```

JSON data

```
{
    "data": {
        "values": [
            {
                "United States - Mining and Quarrying FDI Income Payments": "2011",
                "Million US Dollars": 10.464205107286078
            },
            {
                "United States - Mining and Quarrying FDI Income Payments": "2012",
                "Million US Dollars": 7.647265509216813
            },
            {
                "United States - Mining and Quarrying FDI Income Payments": "2013",
                "Million US Dollars": 4.99844166691154
            },
            {
                "United States - Mining and Quarrying FDI Income Payments": "2014",
                "Million US Dollars": 8.958168128566987
            },
            {
                "United States - Mining and Quarrying FDI Income Payments": "2015",
                "Million US Dollars": 0.5183569136056407
            },
            {
                "United States - Mining and Quarrying FDI Income Payments": "2016",
                "Million US Dollars": 1.7542078562754606
            },
            {
                "United States - Mining and Quarrying FDI Income Payments": "2017",
                "Million US Dollars": 0.7525181448483447
            },
            {
                "United States - Mining and Quarrying FDI Income Payments": "2018",
                "Million US Dollars": 3.829636888742836
            }
        ]
    },
    "title": "United States - Mining and Quarrying FDI Income Payments",
    "mark": {
        "type": "bar",
        "cornerRadiusEnd": 24,
        "width": {
            "band": 0.3
        }
    },
    "width": 850,
    "view": {
        "fill": "grey",
        "stroke": "#aaa",
        "fillOpacity": 0.2,
        "opacity": 0.5
    },
    "encoding": {
        "y": {
            "field": "United States - Mining and Quarrying FDI Income Payments",
            "type": "quantitative"
        },
        "x": {
            "field": "Million US Dollars",
            "type": "quantitative"
        },
        "color": {
            "value": "#dcf04a"
        }
    },
    "config": {
        "axis": {
            "labelFont": "Playbill",
            "titleFont": "Playbill"
        },
        "legend": {
            "labelFont": "Playbill",
            "titleFont": "Playbill",
            "orient": "top",
            "direction": "horizontal"
        },
        "header": {
            "labelFont": "Playbill",
            "titleFont": "Playbill"
        },
        "mark": {
            "font": "Playbill"
        },
        "title": {
            "font": "Playbill",
            "subtitleFont": "Playbill"
        }
    }
}
```

**Comment by domoritz** [comment]
That looks like Vega-Lite, not Vega. You need to use vl2svg.
