### ISSUE TITLE
Fatal crash rendering SVGs on Node

### ISSUE THREAD

**Issue by nyurik** [vega/vega#600]
This graph renders ok in [Vega Editor](https://vega.github.io/vega-editor/?mode=vega) (canvas mode only), but causes a fatal crash in bin/vg2png.  It works if the input is PNG, GIF, or JPEG file.

```json
{
  "data": [
    {
      "name": "data",
      "values": [{}]
    }
  ],
  "marks": [
    {
      "type": "image",
      "from": {"data": "data"},
      "properties": {
        "enter": {
          "url": {"value":"https://en.wikipedia.org/wiki/Special:Redirect/file/Pictogramme_test_1.svg"}
}}}]}
```

Tested with a1e57ff190f7017511d8e5007f47ea5e63b3f5d3:
```bash
/home/yurik/wmf/graphoid/vega/node_modules/vega-scenegraph/src/render/canvas/marks/image.js:29
      g.drawImage(o.image, x, y, w, h);
        ^

Error: Image given has not completed loading
    at Error (native)
    at CanvasRenderer.draw (/home/yurik/wmf/graphoid/vega/node_modules/vega-scenegraph/src/render/canvas/marks/image.js:29:9)
    at CanvasRenderer.prototype.draw (/home/yurik/wmf/graphoid/vega/node_modules/vega-scenegraph/src/render/canvas/CanvasRenderer.js:104:13)
    at CanvasRenderer.draw (/home/yurik/wmf/graphoid/vega/node_modules/vega-scenegraph/src/render/canvas/marks/group.js:51:16)
    at CanvasRenderer.prototype.draw (/home/yurik/wmf/graphoid/vega/node_modules/vega-scenegraph/src/render/canvas/CanvasRenderer.js:104:13)
    at CanvasRenderer.prototype.render (/home/yurik/wmf/graphoid/vega/node_modules/vega-scenegraph/src/render/canvas/CanvasRenderer.js:93:8)
    at View.prototype.render (/home/yurik/wmf/graphoid/vega/src/core/View.js:411:18)
    at wait [as _onTimeout] (/home/yurik/wmf/graphoid/vega/src/core/HeadlessView.js:28:12)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by nyurik** [comment]
Seems like this is actually a missing functionality of Canvas lib https://github.com/Automattic/node-canvas/issues/494, and there are a few people working on it.
