### ISSUE TITLE
vg2png problems with ggvis::extract_png()

### ISSUE THREAD

**Issue by Wario84** [vega/vega#611]
Hi guys, I hope that you can help me.

I don't have experience in Vega, and I have invested some time trying to set it up in Windows 10. I managed to install it, I believe. My goal is to use the vg2png through RStudio using the packages ggvis. I have two questions:

1. **If there are any test commands, that I can run to verify that my installation is correct?**

1. **Using this reproducible example, I would like to know if there is something wrong with my vega or is an R issue?**

_**My R Code**_

```
> library(ggvis)  
> mtcars %>% ggvis(~hp, ~mpg) %>% layer_smooths() %>% export_png(file="plot2.png")
undefined:3
return x["data"]["domain"];
                ^

TypeError: Cannot read property 'domain' of undefined
    at eval [as get] (eval at <anonymous> (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\node_modules\datalib\src\util.js:147:20), <anonymous>:3:17)
    at eval [as add] (eval at create (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\node_modules\datalib\src\aggregate\measures.js:175:23), <anonymous>:3:14)
    at Facetor.proto._add (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\node_modules\datalib\src\aggregate\aggregator.js:158:31)
    at add (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\src\transforms\Aggregate.js:174:31)
    at Array.forEach (native)
    at Aggregate.prototype.transform (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\src\transforms\Aggregate.js:190:13)
    at Aggregate.prototype.evaluate (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\src\transforms\Transform.js:48:15)
    at Node.dataRef (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\src\scene\Scale.js:387:15)
    at Node.domainMinMax (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\src\scene\Scale.js:429:15)
    at Node.quantitative (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\src\scene\Scale.js:223:18)
Warning message:
running command '"C:\Users\mglez\AppData\Roaming\npm\vg2png.cmd" C:\Users\mglez\AppData\Local\Temp\RtmpYrehMI\ggvisb48433155b9/plot.json plot2.png' had status 1
```

Any help will be really appreciated.

**Comment by jheer** [comment]
Hi @Wario84, unfortunately I can't discern the nature of the issue from this report. It looks like an exception is being raised during evaluation of the Vega program, but without access to the specification I don't know what is breaking down. If you happen to have access to the Vega specification that ggvis is generating, we can take a look at that to let you know if this is a Vega problem. Otherwise, I might post the issue with the ggvis team.

I'm closing the issue for now, but feel free to re-open and/or post follow-ups here as needed!
