### ISSUE TITLE
Bundle vega with browserify

### ISSUE THREAD

**Issue by domoritz** [vega/vega#647]
I'm trying to bundle vega using browserify but get an error because vega seems to depend on canvas. I believe that we don't need canvas because we are running in a browser. Do I need to configure my build? 

```
> vega-lite@2.0.0-alpha.0 build:test-gallery /Users/domoritz/Developer/UW/vega-lite
> browserify test-gallery/main.ts -p [tsify -p test-gallery] -d > test-gallery/main.js

Error: Cannot find module '../build/Release/canvas' from '/Users/domoritz/Developer/UW/vega-lite/node_modules/canvas/lib'
    at /Users/domoritz/Developer/UW/vega-lite/node_modules/resolve/lib/async.js:55:21
    at load (/Users/domoritz/Developer/UW/vega-lite/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/domoritz/Developer/UW/vega-lite/node_modules/resolve/lib/async.js:92:31)
    at /Users/domoritz/Developer/UW/vega-lite/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:111:15)
```

**Comment by jheer** [comment]
Can you verify if the addition of the `"browser"` directive in package.json (added by 313725ef758ac4fde2218d385eb80d5bc755f115) fixes the issue for you? Once resolved, I will release a new beta version.

**Comment by domoritz** [comment]
I can compile the test gallery now. Thanks!
