### ISSUE TITLE
png creation problem in v3.0.0-beta*

### ISSUE THREAD

**Issue by alkan** [vega/vega#666]
While running

node_modules/vega/bin/vg2png node_modules/vega/spec/area.vg.json

command  we get the following error:

TypeError: Cannot read property 'getContext' of null
    at resize (/Users/ayhan/projects/matriks/dev/social-net/botanic-charts/node_modules/vega/build/vega.js:10800:23)
    at CanvasRenderer.prototype$38.resize (/Users/ayhan/projects/matriks/dev/social-net/botanic-charts/node_modules/vega/build/vega.js:10841:3)
    at CanvasRenderer.prototype$36.initialize (/Users/ayhan/projects/matriks/dev/social-net/botanic-charts/node_modules/vega/build/vega.js:10439:15)
    at CanvasRenderer.prototype$38.initialize (/Users/ayhan/projects/matriks/dev/social-net/botanic-charts/node_modules/vega/build/vega.js:10836:26)
    at initializeRenderer (/Users/ayhan/projects/matriks/dev/social-net/botanic-charts/node_modules/vega/build/vega.js:23846:6)
    at /Users/ayhan/projects/matriks/dev/social-net/botanic-charts/node_modules/vega/build/vega.js:23913:12

**Comment by jheer** [comment]
Just to sanity check, was node-canvas (an optional dependency for Vega overall, but required for vg2png) successfully installed?

**Comment by jheer** [comment]
Using a clean install of Vega (via `npm install vega` on Mac OS and Node v6.9), I am able to run `node_modules/vega/bin/vg2png node_modules/vega/spec/area.vg.json` without issues.

I'm closing the issue for now. I suspect any issues here are most likely due to the node-canvas module. If so, please see the [node-canvas repository](https://github.com/Automattic/node-canvas/tree/v1.x) for more information and troubleshooting tips. Feel free to respond / re-open with more information if needed!

**Comment by nwhitmont** [comment]
I am experiencing this error with the following code adapted from the example [here](https://vega.github.io/vega/usage/#node).

Note: using the vg2png command-line utility works fine. But this Node.js code to write to PNG file fails with error.

```js
var vega = require('vega');
var fs = require('fs');

// create a new view instance for a given Vega JSON spec
var view = new vega.View(vega.parse(spec))
  .renderer('none')
  .initialize();

  // generate a static PNG image
view.toCanvas()
  .then(function(canvas) {
    // process node-canvas instance
    fs.writeFile('chart.png', canvas.toBuffer())
  })
  .catch(function(err) { console.error(err); });
```

Generates error:
```
TypeError: Cannot read property 'getContext' of null
    at resize (/Users/src/botbuilder-vega/node_modules/vega/build/vega.js:7392:23)
    at CanvasRenderer.prototype$6.resize (/Users/src/botbuilder-vega/node_modules/vega/build/vega.js:7434:3)
    at CanvasRenderer.prototype$4.initialize (/Users/src/botbuilder-vega/node_modules/vega/build/vega.js:7027:15)
    at CanvasRenderer.prototype$6.initialize (/Users/src/botbuilder-vega/node_modules/vega/build/vega.js:7429:26)
    at initializeRenderer (/Users/src/botbuilder-vega/node_modules/vega/build/vega.js:26610:6)
    at /Users/src/botbuilder-vega/node_modules/vega/build/vega.js:26685:16
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
```

Does anyone have a working Node.js example of writing to PNG file?

**Comment by wavefancy** [comment]
With canvas installed I have the same error. 
```
npm view vega version
5.3.5
npm view canvas version
2.4.1
```

```
./vg2pdf test.json test.pdf
TypeError: Cannot read property 'getContext' of null
```

However, no problem when converting to svg.
```
./vg2svg test.json test.svg
```
But the output SVG is not valid
```
<svg class="marks" width="0" height="0" viewBox="0 0 0 0" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g transform="translate(0,0)"><g class="mark-group role-frame root"><g transform="translate(0,0)"><path class="background" d="M0,0h0v0h0Z" style="fill: none;"></path><g></g></g></g></g></svg>
```

```
# test.json
{"config": {"view": {"width": 400, "height": 300}}, "data": {"name": "data-c5b3818a245621ca858cdec1d3885251"}, "mark": "point", "encoding": {"color": {"type": "nominal", "field": "C"}, "x": {"type": "quantitative", "field": "X"}, "y": {"type": "quantitative", "field": "Y"}}, "$schema": "https://vega.github.io/schema/vega-lite/v2.6.0.json", "datasets": {"data-c5b3818a245621ca858cdec1d3885251": [{"C": "c1", "X": 1, "Y": 10, "Z": 1}, {"C": "c2", "X": 2, "Y": -5, "Z": 3}, {"C": "c3", "X": 5, "Y": 3, "Z": 2}]}}
```

**Comment by jzaburunov** [comment]
Have same issue with node 10 on alpine-linux based docker image. When trying to use created Canvas object.

**Comment by emlazzarin** [comment]
+1 on the same issue via an alpine docker image.

**Comment by judepayne** [comment]
@emlazzarin Thx for this. running `npm install -g canvas` also fixed it for me.
