### ISSUE TITLE
[Bug] Unable to write to PNG file with vega@3.0.0-beta.38 Node.js

### ISSUE THREAD

**Issue by nwhitmont** [vega/vega#915]
**System Info**
- `"vega": "^3.0.0-beta.38"`
- Node - v6.10.2
- NPM - v3.10.10
- macOS Sierra

I am experiencing this error with the following code adapted from the example [here](https://vega.github.io/vega/usage/#node).

Note: using the vg2png command-line utility works fine. But this Node.js code to write to PNG file fails with error.

```js
var vega = require('vega');
var fs = require('fs');

// create a new view instance for a given Vega JSON spec
var view = new vega.View(vega.parse(spec))
  .renderer('none')
  .initialize();

  // generate a static PNG image
view.toCanvas()
  .then(function(canvas) {
    // process node-canvas instance
    fs.writeFile('chart.png', canvas.toBuffer())
  })
  .catch(function(err) { console.error(err); });
```

Generates error:
```
TypeError: Cannot read property 'getContext' of null
    at resize (/Users/src/botbuilder-vega/node_modules/vega/build/vega.js:7392:23)
    at CanvasRenderer.prototype$6.resize (/Users/src/botbuilder-vega/node_modules/vega/build/vega.js:7434:3)
    at CanvasRenderer.prototype$4.initialize (/Users/src/botbuilder-vega/node_modules/vega/build/vega.js:7027:15)
    at CanvasRenderer.prototype$6.initialize (/Users/src/botbuilder-vega/node_modules/vega/build/vega.js:7429:26)
    at initializeRenderer (/Users/src/botbuilder-vega/node_modules/vega/build/vega.js:26610:6)
    at /Users/src/botbuilder-vega/node_modules/vega/build/vega.js:26685:16
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
```

Does anyone have a working Node.js example of writing to PNG file?

**Comment by jheer** [comment]
Looks like node-canvas is not installed? If vg2png is working for you than that is most likely the issue.

**Comment by nwhitmont** [comment]
Updated to `vega@.3.0.0-rc2` and no issues. Resolved
