### ISSUE TITLE
Not able to build the node server - Corda(Simm Valuation Demo)

### ISSUE THREAD

**Issue by kamalisengodan-abc** [vega/vega#934]
I attached the log, Kindly let me know to proceed further by overcoming this error.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle vega@0.0.0~prestart: vega@0.0.0
6 silly lifecycle vega@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle vega@0.0.0~start: vega@0.0.0
8 verbose lifecycle vega@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle vega@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\corda\samples\simm-valuation-demo\src\main\web\node_modules\.bin;C:\WINDOWS\CCM\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Users\28774\AppData\Local\Microsoft\WindowsApps
10 verbose lifecycle vega@0.0.0~start: CWD: D:\corda\samples\simm-valuation-demo\src\main\web
11 silly lifecycle vega@0.0.0~start: Args: [ '/d /s /c', 'ng serve' ]
12 silly lifecycle vega@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle vega@0.0.0~start: Failed to exec start script
14 verbose stack Error: vega@0.0.0 start: `ng serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vega@0.0.0
16 verbose cwd D:\corda\samples\simm-valuation-demo\src\main\web\src
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error vega@0.0.0 start: `ng serve`
22 error Exit status 1
23 error Failed at the vega@0.0.0 start script 'ng serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vega package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ng serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vega
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vega
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by wiibaa** [comment]
I would be in favor of closing this one as it relates more to https://github.com/corda/corda and reference obsolete versions of node/npm.
